name: network_kominfo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dbcrypt: ^2.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  image_picker: ^0.7.4
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pdf: ^3.7.1
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
